Document: unity-gtk-module
Title: Debian unity-gtk-module Manual
Author: <insert document author here>
Abstract: This manual describes what unity-gtk-module is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/unity-gtk-module/unity-gtk-module.sgml.gz

Format: postscript
Files: /usr/share/doc/unity-gtk-module/unity-gtk-module.ps.gz

Format: text
Files: /usr/share/doc/unity-gtk-module/unity-gtk-module.text.gz

Format: HTML
Index: /usr/share/doc/unity-gtk-module/html/index.html
Files: /usr/share/doc/unity-gtk-module/html/*.html
