Document: vala-panel
Title: Debian vala-panel Manual
Author: <insert document author here>
Abstract: This manual describes what vala-panel is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vala-panel/vala-panel.sgml.gz

Format: postscript
Files: /usr/share/doc/vala-panel/vala-panel.ps.gz

Format: text
Files: /usr/share/doc/vala-panel/vala-panel.text.gz

Format: HTML
Index: /usr/share/doc/vala-panel/html/index.html
Files: /usr/share/doc/vala-panel/html/*.html
